### ISSUE TITLE
Good review !

### ISSUE THREAD

**Issue by wenhwu** [MinZHANG-WHU/Change-Detection-Review#1]
Thank you for your generous sharing！

This is the most comprehensive review of change detection to date and is more formal than [wenhwu/awesome-remote-sensing-change-detection](https://github.com/wenhwu/awesome-remote-sensing-change-detection). 

I found a small problem, the red underlining in the picture below can be ambiguous.

![Screenshot_1](https://user-images.githubusercontent.com/37108948/83473029-39930f00-a4bb-11ea-8d8f-d52b54185763.png)

Thanks! Hopefully,  this repo will be maintained for a long time.

**Comment by MinZHANG-WHU** [comment]
Thank you for pointing out this issue, and I have fixed it. 

Your CD review repo is also a very good job, providing a lot of reference. In addition, thank you for your affirmation and encouragement.
